### ISSUE TITLE
Error: You have already opened a write transaction in the current process

### ISSUE THREAD

**Issue by chrbala** [chrbala/lmdb-leveldown#5]
Due to the workaround method of getting key ranges, iterators throw the following error: ``Error: You have already opened a write transaction in the current process, can't open a second one.``

This issue can be fixed by https://github.com/Venemo/node-lmdb/issues/116

The issue can be experienced on [this branch](https://github.com/chrbala/lmdb-leveldown/tree/chrbala) due to the removal of pessimistic error catching.

**Comment by Venemo** [comment]
Note that you don't need a write transaction for this.

**Comment by chrbala** [comment]
Resolved with [v0.0.3](https://github.com/chrbala/lmdb-leveldown/releases/tag/v0.0.3).
